# Generated by Django 5.0.6 on 2026-09-21 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('abierta', 'En proceso'), ('ganada', 'Ganado'), ('perdida', 'Perdido')], default='abierta', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='agente',
            field=models.ForeignKey(blank=True, help_text='Dueño del contacto. Se mantiene sincronizado con el agente de su conversación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='etapa_actualizada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='contacts.etapa'),
        ),
        migrations.CreateModel(
            name='HistorialContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('etapa', 'Cambio de etapa'), ('agente', 'Cambio de agente')], max_length=10)),
                ('valor_anterior', models.CharField(blank=True, max_length=150)),
                ('valor_nuevo', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contacts.contacto')),
                ('etapa_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contacts.etapa')),
                ('usuario', models.ForeignKey(blank=True, help_text='Vacío = cambio automático del sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de contacto',
                'verbose_name_plural': 'Historial de contactos',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
