# Generated by Django 5.0.6 on 2026-09-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_datos_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo de archivo',
                'verbose_name_plural': 'Motivos de archivo',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='archivado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contacto',
            name='archivado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='archivado_comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='archivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialcontacto',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historialcontacto',
            name='tipo',
            field=models.CharField(choices=[('etapa', 'Cambio de etapa'), ('agente', 'Cambio de agente'), ('archivo', 'Archivado / desarchivado')], max_length=10),
        ),
        migrations.AddField(
            model_name='contacto',
            name='archivado_motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='contacts.motivoarchivo'),
        ),
    ]
