# Generated by Django 5.1 on 2026-06-02 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution_api_url', models.CharField(default='http://evolution-api:8080', max_length=300)),
                ('evolution_api_key', models.CharField(blank=True, max_length=300)),
                ('evolution_instance_name', models.CharField(default='waply', max_length=100)),
                ('webhook_token', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='LogAPIWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('request_body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True)),
                ('duracion_ms', models.IntegerField(null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log API',
                'verbose_name_plural': 'Logs API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaHSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cuerpo', models.TextField(help_text='Usar {{1}}, {{2}}... para variables.')),
                ('variables', models.JSONField(blank=True, default=list)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200)),
                ('ultimo_mensaje_at', models.DateTimeField(blank=True, null=True)),
                ('mensajes_no_leidos', models.PositiveIntegerField(default=0)),
                ('ventana_activa', models.BooleanField(default=False)),
                ('ventana_expira_at', models.DateTimeField(blank=True, null=True)),
                ('bot_crm_activo', models.BooleanField(default=True)),
                ('bot_n8n_activo', models.BooleanField(default=True)),
                ('archivada', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-ultimo_mensaje_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('direccion', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('document', 'Documento'), ('audio', 'Audio'), ('video', 'Video'), ('template', 'Plantilla'), ('interactive', 'Interactivo')], default='text', max_length=20)),
                ('contenido', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=1000)),
                ('media_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('error_detalle', models.TextField(blank=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp.conversacion')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
    ]
