# Generated by Django 5.0.6 on 2026-10-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_conversacion_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('keyword', models.CharField(help_text='Texto pre-cargado que manda el usuario al clickear el ad. Se usa para detectar la campaña automáticamente.', max_length=500)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='telefono_negocio',
            field=models.CharField(blank=True, help_text='Número de WhatsApp del negocio con código de país, ej: +5491155667788. Se usa para generar links de campañas.', max_length=30),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='campana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='whatsapp.campana', verbose_name='Campaña'),
        ),
    ]
