# Generated by Django 5.0.6 on 2026-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='ingreso_por_link',
            field=models.BooleanField(default=False, help_text='El primer mensaje vino a través de un link de WhatsApp (wa.me).'),
        ),
    ]
